{% set name = "datarobot-bp-workshop" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datarobot-bp-workshop-{{ version }}.tar.gz
  sha256: 355697622e833de63008bc0b7470f37081601d2b3c46ecd8aa4471da1806a8b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - datarobot >=2.27.0,<4
    - pandas <1.3.6,>=0.15
    - python-graphviz >=0.16,<1
    - typing-extensions ==4.3.0
    - networkx >=2.2
    - python >={{ python_min }}

test:
  imports:
    - datarobot_bp_workshop
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://blueprint-workshop.datarobot.com
  summary: This client library is designed to support building DataRobot blueprints.
  license: LicenseRef-Modified-BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danna-naser
